package com.jitong.im.audit;

public enum SecurityAuditEventType {
    LOGIN,
    LOGOUT,
    PASSWORD_RESET,
    TOKEN_REPLAY,
    DEVICE_REPLACEMENT,
    CONTACT_BLOCK,
    GROUP_MEMBERSHIP_CHANGE,
    GROUP_ROLE_CHANGE,
    GROUP_BLACKLIST_CHANGE,
    MESSAGE_MODERATION,
    GROUP_AI_POLICY_CHANGE,
    ACCOUNT_DELETION,
    AI_MODEL_USAGE
}
