package com.jitong.im.audit;

public enum SecurityAuditEventType {
    REGISTER,
    LOGIN,
    LOGOUT,
    PASSWORD_CHANGE,
    PASSWORD_RESET,
    TOKEN_REPLAY,
    DEVICE_REPLACEMENT,
    CONTACT_BLOCK,
    CONTACT_UNBLOCK,
    C2C_AI_POLICY_CHANGE,
    GROUP_MEMBERSHIP_CHANGE,
    GROUP_ROLE_CHANGE,
    GROUP_PROFILE_CHANGE,
    GROUP_BLACKLIST_CHANGE,
    GROUP_DISSOLUTION,
    MESSAGE_MODERATION,
    GROUP_AI_POLICY_CHANGE,
    ACCOUNT_DELETION,
    AI_MODEL_USAGE,
    AI_MODEL_FAILURE,
    ABUSE_REPORT_CREATED,
    ABUSE_REPORT_REVIEWED,
    USER_SUSPENSION,
    GROUP_SUSPENSION
}
